#!/bin/bash

SUT=$(realpath $(dirname $0)/../nshar.sh)
SOURCE=$(dirname $SUT)

setupTests() {
  temp=`mktemp -d -t XXXXX`
  cd "$temp"
  mkdir archive
  cp -a $SOURCE archive/ 
  $SUT $* -- archive > nshar-test.run && chmod +x nshar-test.run
}


testQuiet()
{
  setupTests  --exclude .git

  ./nshar-test.run --quiet
  assertEqual $? 0
}

testGzip()
{
  setupTests --gzip --exclude .git
  
  ./nshar-test.run --list
  assertEqual $? 0
}

testCompress()
{
  setupTests --compress --exclude .git

  ./nshar-test.run --list
  assertEqual $? 0
}

testBzip2()
{
  setupTests --bzip2 --exclude .git
  
  ./nshar-test.run --list
  assertEqual $? 0
}

source $(realpath $(dirname $0))/bashunit/bashunit.bash
