#!/bin/bash

SUT=$(realpath $(dirname $0)/../nshar.sh)

setupTests() {
  temp=$(mktemp -d -t XXXXX)
  pushd "${temp}"
  mkdir -p src/.git
  echo "echo This is a test" > src/startup.sh
}

tearDown() {
  popd
  rm -rf "${temp}"
}

testTarExtraOpts() {
  setupTests

  tar_extra="--verbose --exclude .git"
  ${SUT} $tar_extra src > src.sh

  assertEqual $? 0

  tearDown
}

source $(realpath $(dirname $0))/bashunit/bashunit.bash
