language: c
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y realpath pbzip2
script:
- ./make-release.sh
- cd test
- "./extracttest"
- "./tarextratest"
- "./whitespacetest"
- cd ..
deploy:
  provider: releases
  api_key:
    secure: --
  file_glob: true
  file: nshar-*.shar
  skip_cleanup: true
  on:
    repo: andriyg76/nshar
    tags: true
